export const CHATS_FETCH_INIT = 'CHATS_FETCH_INIT';
export const CHATS_FETCH_SUCCESS = 'CHATS_FETCH_SUCCESS';
export const CHATS_FETCH_RESET = 'CHATS_FETCH_RESET';

export const CHATS_SET_ACTIVE_CHAT = 'CHATS_SET_ACTIVE_CHAT';
export const CHATS_SET_ACTIVE_CHAT = 'CHATS_SET_ACTIVE_CHAT';
export const CHATS_UPDATE_USER_STATE = 'CHATS_UPDATE_USER_STATE';

export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CHATS_JOIN_SUCCESS = 'CHATS_JOIN_SUCCESS';
export const CHATS_SET_ACTIVE_CHAT = 'CHATS_SET_ACTIVE_CHAT';
export const CHATS_MESSAGE_SENT = 'CHATS_MESSAGE_SENT';
export const CHATS_SET_MESSAGES = 'CHATS_SET_MESSAGES';
export const CHATS_REGISTER_MESSAGE_SUB = 'CHATS_REGISTER_MESSAGE_SUB';

export const CONNECTION_USER_STATUS_CHANGED = 'CONNECTION_USER_STATUS_CHANGED';

export const SETTINGS_UPDATE = 'SETTINGS_UPDATE';
export const SETTINGS_INITIAL_LOAD = 'SETTINGS_INITIAL_LOAD';

export const AUTH_REGISTER_INIT = 'AUTH_REGISTER_INIT';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';

export const AUTH_ON_INIT = 'AUTH_ON_INIT'; // dispatched at start of app
export const AUTH_ON_SUCCESS = 'AUTH_ON_SUCCESS';
export const AUTH_ON_ERROR = 'AUTH_ON_ERROR';

export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const APP_IS_ONLINE = 'APP_IS_ONLINE';
export const APP_IS_OFFLINE = 'APP_IS_OFFLINE';
